/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;
import KNN.FileToList;
import KNN.Instance;
import KNN.Prediction;

/**
 *
 * @author AMRAOUI
 */
public class four extends javax.swing.JFrame {

    /**
     * Creates new form four
     */
    public four() {
        initComponents();
         Color cr =new Color(249, 235, 200);
        getContentPane().setBackground(cr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        K = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tt = new javax.swing.JTextArea();
        P = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cross Validation");
        setBackground(new java.awt.Color(0, 0, 0));

        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(173, 139, 115));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Prédire");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tt.setColumns(20);
        tt.setRows(5);
        jScrollPane1.setViewportView(tt);

        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });

        jLabel1.setText("Partitionner");

        jLabel2.setText("La valeur de K");

        jButton2.setBackground(new java.awt.Color(173, 139, 115));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Retour");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(P, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(583, 583, 583)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String chemin ="src\\KNN\\weather.nominal.arff";  // chemin du corpus
        FileToList fichier=new FileToList(chemin);
        List<Instance> listeInstances = fichier.lireFichier();
        List <Instance> listApprentissage= new ArrayList <Instance>();
        List <Instance> listTest= new ArrayList <Instance>();
        Scanner s= new Scanner(System.in);
        int partition;
        //System.out.println("Entrer le nombre de folds : ");
        //partition = s.nextInt();
        //System.out.println("\n Entrer la valeur de K : ");
        int KK;

        int k,i ;
        partition=Integer.parseInt(P.getText());
        KK=Integer.parseInt(K.getText());
        double  pourcentage = 0.8;

        listeInstances = fichier.lireFichier();
        int size=listeInstances.size()/partition;
        int trainSize=(int) Math.round(listeInstances.size()*pourcentage);
        int TestSize=listeInstances.size()-trainSize;
        System.out.println("Affichage des instances d'Apprentissage :");
        for(i=0;i<trainSize;i++){
            listApprentissage.add(new Instance(listeInstances.get(i).attributs,listeInstances.get(i).valuesClass));
            System.out.println(Arrays.asList(listApprentissage.get(i).attributs)+" "+listApprentissage.get(i).valuesClass);
        }
        for(i=trainSize;i<listeInstances.size();i++){
            listTest.add(new Instance(listeInstances.get(i).attributs,listeInstances.get(i).valuesClass));
        }
        System.out.println("\n Affichage des instances de Test :");
        for(int j=0;j<listTest.size();j++){
            System.out.println(Arrays.asList(listTest.get(j).attributs)+" "+listTest.get(j).valuesClass);
        }
        Collections.shuffle(listeInstances);



        for(i=0;i<partition;i++) {
            for(k=i*size;k<(i+1)*size;k++) {
                //System.out.println("c'est literation "+i +"de l'ensemble"+k);
                listTest.add(new Instance(listeInstances.get(k).attributs,listeInstances.get(k).valuesClass));
                listApprentissage=listeInstances;
                listApprentissage.remove(new Instance(listeInstances.get(k).attributs,listeInstances.get(k).valuesClass));
            }
            System.out.println("\n");
            int[][] mat= new int[2][2];
            mat =Prediction.Matrix(listApprentissage,listTest,3);
            System.out.println();
            System.out.println("------------------------------------------------");
            System.out.println(" La matrice de confision :");
            for(int j=0;j<2;j++) {
                for(int r=0;r<2;r++) {

                    System.out.print("\t"+mat[j][r]+"\t"+"|");
                }
                System.out.println("\n");
            }
             String mat1 = Integer.toString(mat[0][0]);
        String mat2 = Integer.toString(mat[0][1]);
        String mat3 = Integer.toString(mat[1][0]);
        String mat4 = Integer.toString(mat[1][1]);

            double x= Prediction.Exactitude(mat, listTest.size());
            System.out.println("l'exactitude est : "+ x);
            System.out.println("\n");
            double y=Prediction.Précision(mat,0);
            System.out.println("la precision de la classe 1 est : "+ y);
            double y1=Prediction.Précision(mat,1);
            System.out.println("la precision de la classe 2 est : "+ y1);
            System.out.println("\n");
            double z=Prediction.Rappel(mat,0);
            System.out.println("le rappel de la classe 1 est : "+ z);
            double z1=Prediction.Rappel(mat,1);
            System.out.println("le rappel de la classe 2 est : "+ z1);
            System.out.println("\n");
            double f= Prediction.F_mesure(y, z);
            System.out.println("la f mesure de la classe 1 est : "+ f);
            double f1= Prediction.F_mesure(y1, z1);
            System.out.println("la f mesure de la classe 2 est : "+ f1);
            tt.append("-----------------------------------------------------------------------------------------"+"\n\n"+"l'exactitude est : "+String.valueOf(x)+"\n"
+"\nla precision de la classe 1 est : "+String.valueOf(y)+"\n"
+"la precision de la classe 2 est : "+String.valueOf(y1)+"\n\n"
+"le rappel de la classe 1 est : "+String.valueOf(z)+"\n"
+"le rappel de la classe 2 est : "+String.valueOf(z1)+"\n\n"
+"la f mesure de la classe 1 est : "+String.valueOf(f)+"\n"
+"la f mesure de la classe 2 est : "+ String.valueOf(f1)+"\n\n"
+"\n"+"========> La matrice de confision <========="+"\n"+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "
        +" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+mat1+" "+" "+" "+"|"+" "+" "+" "+mat2+"\n"+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "
        +" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+mat3+" "+" "+" "+"|"+" "+" "+" "+mat4+"\n");
        }
        System.out.println(" ");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new second().setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(four.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(four.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(four.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(four.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new four().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField K;
    private javax.swing.JTextField P;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tt;
    // End of variables declaration//GEN-END:variables
}
