/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import KNN.Distances;
import KNN.FileToList;
import KNN.Instance;
import KNN.Main;
import KNN.Prediction;

/**
 *
 * @author AMRAOUI
 */
public class tree extends javax.swing.JFrame {

    /**
     * Creates new form tree
     */
    public tree() {
        initComponents();
         Color cr =new Color(249, 235, 200);
        getContentPane().setBackground(cr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        url = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        testapp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Partitionnement");

        jButton1.setBackground(new java.awt.Color(173, 139, 115));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Prédire");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        url.setColumns(20);
        url.setRows(5);
        jScrollPane1.setViewportView(url);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("K :");

        jButton2.setBackground(new java.awt.Color(173, 139, 115));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Retour");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        testapp.setColumns(20);
        testapp.setRows(5);
        jScrollPane2.setViewportView(testapp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String sc = new second().getUrl2();

      String chemin ="src\\KNN\\weather.nominal.arff";  // chemin du corpus
        testapp.setText("");
        FileToList fichier=new FileToList(chemin);
        Distances distances=new Distances();
        List<Instance> listeInstances = fichier.lireFichier();
        Collections.shuffle(listeInstances);
        //double [] attribute=new double[]{37,16,22};
        List<Instance> listApprentissage =new ArrayList<Instance>();
        List<Instance> listTest =new ArrayList<Instance>();
        double pourcentage=0.8;
        int nombreErreur=0,i,k;
        int trainSize=(int) Math.round(listeInstances.size()*pourcentage);
        int TestSize=listeInstances.size()-trainSize;
        
        System.out.println("Affichage des instances d'Apprentissage :");
        testapp.append("Affichage des instances d'Apprentissage :"+"\n");
        for(i=0;i<trainSize;i++){
            listApprentissage.add(new Instance(listeInstances.get(i).attributs,listeInstances.get(i).valuesClass));
            
           System.out.println(Arrays.asList(listApprentissage.get(i).attributs)+" "+listApprentissage.get(i).valuesClass);
           testapp.append(Arrays.asList(listApprentissage.get(i).attributs)+" "+listApprentissage.get(i).valuesClass+"\n");
        }

        for(i=trainSize;i<listeInstances.size();i++){
            listTest.add(new Instance(listeInstances.get(i).attributs,listeInstances.get(i).valuesClass));
        }
        System.out.println("\n Affichage des instances de Test :");
        testapp.append("\n Affichage des instances de Test :"+"\n");
        for(int j=0;j<listTest.size();j++){
            System.out.println(Arrays.asList(listTest.get(j).attributs)+" "+listTest.get(j).valuesClass);
            
            
            testapp.append(Arrays.asList(listTest.get(j).attributs)+" "+listTest.get(j).valuesClass+"\n");
        }         int kk =Integer. parseInt(jTextField1.getText());
        for(i=0;i<listTest.size();i++){
            System.out.println("==================>##################<==================");
            List<Distances> listeResultats=distances.calculeDistance(listApprentissage, listTest.get(i).attributs);
            String resultat=distances.classeInstance(listeResultats,kk);
            if(!resultat.equals(listTest.get(i).valuesClass)){
                
                nombreErreur++;
            }else continue;
        }
        System.out.println("\n nombre d'erreur est : "+nombreErreur);


        System.out.println("\n");
        int[][] mat= new int[2][2];
       
        mat =Prediction.Matrix(listApprentissage,listTest,kk);
        System.out.println();
        System.out.println("------------------------------------------------");
        System.out.println(" La matrice de confision :");
        for(int j=0;j<2;j++) {
            for(int r=0;r<2;r++) {
                
                System.out.println(mat[j][r]+"\t");
                
            }
            
            System.out.println("\n");
        }
        String mat1 = Integer.toString(mat[0][0]);
        String mat2 = Integer.toString(mat[0][1]);
        String mat3 = Integer.toString(mat[1][0]);
        String mat4 = Integer.toString(mat[1][1]);
        

        double x= Prediction.Exactitude(mat, listTest.size());
        System.out.println("l'exactitude est : "+ x);
        System.out.println("\n");
        double y=Prediction.Précision(mat,0);
        System.out.println("la precision de la classe 1 est : "+ y);
        double y1=Prediction.Précision(mat,1);
        System.out.println("la precision de la classe 2 est : "+ y1);
        System.out.println("\n");
        double z=Prediction.Rappel(mat,0);
        System.out.println("le rappel de la classe 1 est : "+ z);
        double z1=Prediction.Rappel(mat,1);
        System.out.println("le rappel de la classe 2 est : "+ z1);
        System.out.println("\n");
        double f= Prediction.F_mesure(y, z);
        System.out.println("la f mesure de la classe 1 est : "+ f);
        double f1= Prediction.F_mesure(y1, z1);
        System.out.println("la f mesure de la classe 2 est : "+ f1);
        System.out.println("la valleur de k est : "+jTextField1.getText());
        System.out.println(sc);
        

url.setText("-----------------------------------------------------------------------------------------"+"\n\n"+"l'exactitude est : "+String.valueOf(x)+"\n"
+"\nla precision de la classe 1 est : "+String.valueOf(y)+"\n"
+"la precision de la classe 2 est : "+String.valueOf(y1)+"\n\n"
+"le rappel de la classe 1 est : "+String.valueOf(z)+"\n"
+"le rappel de la classe 2 est : "+String.valueOf(z1)+"\n\n"
+"la f mesure de la classe 1 est : "+String.valueOf(f)+"\n"
+"la f mesure de la classe 2 est : "+ String.valueOf(f1)+"\n\n"
+"\n"+"========> La matrice de confision <========="+"\n"+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "
        +" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+mat1+" "+" "+" "+"|"+" "+" "+" "+mat2+"\n"+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "
        +" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+" "+mat3+" "+" "+" "+"|"+" "+" "+" "+mat4+"\n");

       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new second().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea testapp;
    private javax.swing.JTextArea url;
    // End of variables declaration//GEN-END:variables
}
